### ISSUE TITLE
FindElements throws StaleElementReferenceException

### ISSUE THREAD

**Issue by M0ns1gn0r** [Dreamescaper/DotNetSeleniumExtras.Core#4]
https://github.com/Dreamescaper/DotNetSeleniumExtras.Core/blob/23c4cac031558966de2e6fa6f731806a9328d5ae/src/PageObjects/ByChained.cs#L92

This line may lead to `StaleElementReferenceException` although `FindElements` should be a safe method that doesn't throw.

Probably a `try` with an empty `catch` would be OK here.

**Comment by Dreamescaper** [comment]
You're right, thanks for reporting (and sorry for delay).
Should be fixed in latest version.
