### ISSUE TITLE
call the PageFactory.InitElements(Driver, this), throw exception

### ISSUE THREAD

**Issue by namilkimfree** [Dreamescaper/DotNetSeleniumExtras.Core#5]
Method 'GetDomAttribute' in type 'SeleniumExtras.PageObjects.WebElementProxy' from assembly 'SeleniumExtras.PageObjects, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

version: 4.0.0-beta1
OS: windows 10
SDK: net core 3.1

**Comment by Dreamescaper** [comment]
Probably something has changed with WebDriver update.
Will take a look!

**Comment by Dreamescaper** [comment]
I've published updated package version 4.0.0-beta4, the issue should be fixed in that one.

**Comment by namilkimfree** [comment]
thank you, Updating WebDriver solved the problem.

@Dreamescaper
