### ISSUE TITLE
PageFactory's Can I set the Timeout setting?

### ISSUE THREAD

**Issue by namilkimfree** [Dreamescaper/DotNetSeleniumExtras.Core#6]
Is that possible to combine PageFactory approach with a custom searching process such as 3 tries for searching with an ExpectedCondition being set and so on?

PageFactory.initElements(new DefaultPageObjectMemberDecorator(driver, 15), this);

or

 PageFactory.initElements(new AppiumFieldDecorator(driver, Duration.ofSeconds(30)), this);

**Comment by Dreamescaper** [comment]
Generally it will use same search settings as provided ISearchContext (e.g. your driver).
If you want to customize it somehow, you can wrap it in your own ISearchContext implementation, e.g. something like that:
```csharp
    public class RetryingSearchContext : ISearchContext
    {
        private readonly ISearchContext innerContext;

        public RetryingSearchContext(ISearchContext innerContext)
        {
            this.innerContext = innerContext;
        }

        public IWebElement FindElement(By by)
        {
            for (int i = 0; ; i++)
            {
                try
                {
                    return innerContext.FindElement(by);
                }
                catch (NoSuchElementException)
                {
                    if (i == 3)
                    {
                        throw;
                    }
                }
            }
        }

        public ReadOnlyCollection<IWebElement> FindElements(By by)
        {
            return innerContext.FindElements(by);
        }
    }
```

**Comment by Dreamescaper** [comment]
Closing as answered, let me know if you have other questions.
