### ISSUE TITLE
Able to get IWebElement, but I am not able to get IWebElements

### ISSUE THREAD

**Issue by manikumarnune123** [Dreamescaper/DotNetSeleniumExtras.Core#9]
Currently I am using below code to get a single web element which is equivalent to driver.FindElement(), is there a way to get a array of web elements equivalent to driver.FindElements()

[FindsBy(How=How.Id,Using = "twotabsearchtextbox")]
private IWebElement _searchInputBox;

**Comment by Dreamescaper** [comment]
You can use `IList<IWebElement>` property type.

**Comment by manikumarnune123** [comment]
@Dreamescaper  Yes, it's working. Thanks for the answer and for the nuget. Do you have any link where I can learn about this whole repo Attributes, Properties and Methods? I will close the issue.
